### PR TITLE
Reorganize repo into two subfolders

### PR DESCRIPTION
**Pull request by antoniovazquezblanco**
In https://github.com/KiCad/kicad-templates/pull/13 we concluded that a reorganization of the template repo was needed.

I have splitted templates into projects and worksheets and updated CMake scripts accordingly. BEWARE I am not fluent in CMake language and I don't know the best language practices. Please check that in depth.

Also, default template file may have moved and that could require devs intervention.

Any improvements sugestions or comments? Thanks!

### CODE REVIEW

**Comment by poeschlr** [comment]
I suggest you ask over at the mailing list for support by the packagers.

**Comment by antoniovazquezblanco** [comment]
https://lists.launchpad.net/kicad-developers/msg40874.html

**Comment by adamwolf** [comment]
Hi! I'm a macOS packager.  Where should the files go compared to where they go now?

**Comment by poeschlr** [comment]
We are not necessarily suggesting that the current organization of the packages should change in v5. Yes the cmake file is easier if the repo and the resulting file structure in the package are equal. 

But why not use the cmake file as an abstraction layer that allows us to make the repo more organized while keeping the version 5 packages unchanged? The alternative is we branch the v5 stuff and add new worksheet packages only to version 6. (Freezing the version 5 templates at the current state.) Will then however require a change in file structre organization in current nightlies. (Again the abstraction layer could allow this to happen slowly.)

---

Also remember the library tables are already taken from a different structure than this repo (they come directly from the library repos) so we already have an abstraction layer in place. This reorg would just extend the same philosophy to the template repo.

---

i would assume that it will make sense to reorganize the template folder for v6 in general. If we have a lot more templates for both projects and page layouts then it will become quite unwieldy with the current file structure. (Again something that should be completely independent from the organization of this repo.)

**Comment by antoniovazquezblanco** [comment]
The decision on what can go into V5 and V6 is not mine and I will respect whatever the devs decide. Given that, I was thinking that the templates folder should be split into two categories, one for projects and one for worksheet templates. I think that the idea made sense from the development and the user point of view.

Do you guys think that this could be reasonable for V5? If not, would this be reasonable for V6 and do you have a suggestion for a temporary V5 solution? If no temporary solution is given, we will freeze some additions in the repo till V6.

**Comment by poeschlr** [comment]
As i explained above: There should not be any change to the resulting output if we do it right. (The cmake file simply needs to be written that way. It looks like the cmake changes you made would fulfill this requirement. But that would be up to a packager to test.)

**Comment by antoniovazquezblanco** [comment]
Ok, for this to go into V5 I have to implement the following:

> There should not be any change to the resulting output if we do it right.

I will do that as soon as I find a time slot.

That solves the issue of maintenance for us but the user will be facing the problem that will not be able to distinguish a folder containing a template project and a folder with worksheet files.

**Comment by antoniovazquezblanco** [comment]
Done

**Comment by stambaughw** [comment]
As long as the final install paths when running `make install` are not
changed, there should not be any issues.  Otherwise, the package
builders would be affected and that would not be acceptable for V5.  For
V6, we can discuss changes to install locations if that is necessary but
that will require some coordination with the development team.

Cheers,

Wayne

**Comment by poeschlr** [comment]
@adamwolf would you be prepared to test if this does indeed not change the resulting install paths (at least for the mac build)? 

Maybe also somebody from the linux builders and windows builders? (@nickoe are you still involved in the windows builder or do i remember this wrong?)

**Comment by adamwolf** [comment]
Yeah, I can definitely test it.

**Comment by antoniovazquezblanco** [comment]
Solves https://github.com/KiCad/kicad-templates/issues/14

**Comment by antoniovazquezblanco** [comment]
@adamwolf Have you had the chance to test this? :)

**Comment by adamwolf** [comment]
I'm so sorry.  I did not realize it was in a state where it was ready for me to test.

**Comment by adamwolf** [comment]
I am running the test today.

**Comment by adamwolf** [comment]
This works completely fine on macOS.

**Comment by antoniovazquezblanco** [comment]
Thank you!

**Comment by antoniovazquezblanco** [comment]
Any other packager that may want to test this? @nickoe?

**Comment by antoniovazquezblanco** [comment]
Does anyone feel confortable enough to merge this PR?

**Comment by nickoe** [comment]
Sorry for my lack of response. I forgot this again. To there is no problem as long as the install is handled by cmake.

**Comment by poeschlr** [comment]
As i did not get a clear "no go" i simply choose to interpret them as "go". Well lets see if anyone complains once this is merged.

**Comment by antoniovazquezblanco** [comment]
Thanks!

**Pull request merged**
