### PR TITLE
GOST worksheets update.

### PR DESCRIPTION
**Pull request by baranovskiykonstantin**

### CODE REVIEW

**Comment by baranovskiykonstantin** [comment]
1. New fields (%C4, %C5) was added to the stamp (the table in the bottom right corner of the sheet).
2. Font style was changed from italic to regular. The default font style of a schematic is regular, so the font style of the worksheets was changed to be consistent.
worksheetchanges

**Comment by baranovskiykonstantin** [comment]
@antoniovazquezblanco, who is "pending reviewer"? How can I speed up the process?

**Comment by antoniovazquezblanco** [comment]
Your contribution needs to be reviewed. That tag indicates that no librarian has yet assigned himself to your pull request. Whenever someone finds the time to review your work, that tag will dissapear.

The only way to speed up that process is to free work from other librarians. Feel free to try and review other contributions if you feel like it ;)

**Comment by eldarkg** [comment]
@antoniovazquezblanco Verified. Looks good

**Comment by chschlue** [comment]
Ok then. Merging.

**Pull request merged**
