### PR TITLE
Copy templates

### PR DESCRIPTION
**Pull request by SchrodingersGat**
This PR copies all template files across from the legacy kicad-library repo

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@poeschlr

**Comment by poeschlr** [comment]
I assume all templates will need work once we finished moving all the footprint and symbol libs. (they might reference footprints and symbols that do no longer exist that way in the new lib.)

My worry is that we will forget about that.

**Comment by poeschlr** [comment]
There is now a conflict for some reason.

How do we best convert these templates over to use the new footprints?
Do we need to manually run the remap process on these? (should they first be made to use the new library to ensure that remapping works?)

**Comment by SchrodingersGat** [comment]
It's in conflict as I copied all the templates across so that the devs could package them with cmake. I'll close this PR but the changes you suggest still need to be made.

**Pull request closed without merging**
