### PR TITLE
Fix incorrect SDA and SCL pin on Raspberry pi hat EEPROM

### PR DESCRIPTION
**Pull request by jessekerkhoven**

### CODE REVIEW

**Comment by evanshultz** [comment]
@jessekerkhoven 
Hi and welcome.

The diff shows quite a lot of changes, but these may be simply from opening, fixing, and saving the template. Can you please detail what you changed? What was wrong with those pins? What did you change to fix the issue?

Screenshots would be very, very helpful. Both of the schematic and the board.

Thanks!

**Comment by jessekerkhoven** [comment]
Thanks. On the original files the SDA and SCL pin where swapped, what resulted in a non working eeprom on our prototype hat. See pictures below:
before


You are correct. The changes are only coming from swapping the SDA and SCL connections in the schematics on the eeprom. I also reflected this changes on the pcb by rewiring the corresponding connections. I was also amazed on the amount of changes, so i did this with a clean base and only change the required connections in one time to get a clean as possible commit. 

Result:
after

**Comment by evanshultz** [comment]
Thanks for all the details! Now I can see clearly what you saw and what you changed.

Checked https://www.onsemi.jp/PowerSolutions/document/CAT24C32-D.PDF and https://github.com/raspberrypi/hats/blob/master/designguide.md to confirm, and opening the project all looks good with your fix too.

I appreciate catching this error and taking the time to fix it. And I'm sorry that your hat didn't work because of this error.

One question for anyone (@poeschlr , maybe?): there is a popup dialog when the project is opened and several symbols are rescued. Does any of this need to be fixed? I realize the template correction is important to get into the library but I want to check on updates before I merge.

**Comment by jessekerkhoven** [comment]
Thanks for the writeup. I hope it will be merged soon, before other people have a busted hat.

The popup dialog with symbol rescued, are happing if you choose a different name than the original project (raspberrypi_hat).  I believe something is wrong with the template copy action and linking all libraries. The library raspberrypi_hat.lib is renamed to your new project name but the links in the schema won't. But i didn't look into it yet.

**Comment by evanshultz** [comment]
@KiCad/librarians 
I'm going to merge this in several hours if there's no comments. I can't much discussion about templates in general, including their maintenance, but this PR looks OK in 5.1.2 and I don't want to let this error linger when a fix is ready.

**Comment by antoniovazquezblanco** [comment]
I agree.

Thanks!

**Comment by evanshultz** [comment]
Alright. Here goes...

**Comment by evanshultz** [comment]
@jessekerkhoven 
Sorry that this template had a clear error, and thanks for taking the time to fix it! Much appreciated!

**Pull request merged**
