### PR TITLE
Update templates for new lib plus remap

### LINKED ISSUE #4: The templates need to be converted over to use the new libs and the sym-lib-table
How do we best convert these templates over to use the new footprints?
Do we need to manually run the remap process on these? (should they first be made to use the new library to ensure that remapping works?)

### PR DESCRIPTION
**Pull request by poeschlr**
This will fix #4 and make the template repo ready for the v5 release.

### CODE REVIEW

**Comment by poeschlr** [comment]
@evanshultz or @jkriege2 could one of you take a look at this? This is one of the main things still open before we can think about a version 5 release.

**Comment by evanshultz** [comment]
I opened all of them and they look workable. I didn't compare the schematic, header pinouts, board outlines, or mounting hole size/location with the actual board requirements so I can't comment on correctness.

For many of these templates I suspect that the pin names, text notes, symbol rotation, mounting holes, etc. could use a bit of polish and standardization, but that isn't a showstopper to me.

Feedback:
1. All schematics seem to open fine in 4.0.7 but give an error. I know this is a v5 library and we already talked about this topic for sch libraries so I'm just sharing what I see.
1. Should `1593K_Enclosure` specify the manufacturer, such as `Hammond_1593K_Enclosure`?
1. Why `Arduino_As_Uno_R3` and not just `Arduino_Uno_R3`?
1. The following don't have the headers in a box on the schematic: `BeagleBone-Black-Cape`, `minnowboard-ls-lure`, `raspberrypi_hat`, `raspberrypi-gpio`, `raspberrypi-gpio-40pin`, `stm32f100-discovery-shield`, `ti-stellaris-boosterpack40_min`.
1. The following board doesn't open in v4: `minnowboard-ls-lure`.
1. `raspberrypi_hat` has a symbol called `40HAT` which is rather non-descriptive. What if another version of the Rasp Pi had a different pinout? Or another template needed a 40-pin header? Contrast this with `raspberrypi-gpio-40pin` (and the templates above) which uses a generic header.
1. Similarly, `ti-stellaris-boosterpack40_min` also has specific named headers instead of generic ones.
1. `raspberrypi_hat` board could also include the locations of the camera and display cutout on some info layer as a guide. The routing isn't exactly spectacular, to be honest. Lastly, this board doesn't have the zones refreshed and upon opening it shows a short:
image
1. `raspberrypi-gpio` board has a text note that P1 should be on the bottom of the board, so why isn't it placed there? For whatever reason it's on the top. `raspberrypi-gpio-40pin` does this properly.
1. Only a few of the board templates indicate which side of the board should be up (or against the mother board?) when the shield is used. Or which side the headers go on. Is this kind of information important enough to be documented on each board?
1. `stm32f100-discovery-shield` has a zone poured. Is it better to leave that all up to the user?

Was there something specific you wanted to be checked?

Lastly, you commented at  that the DIN lib wasn't moved. Is that also a blocker for v5 release?

**Comment by poeschlr** [comment]
The v5 release could go on without the din lib but it would be a good idea to include it. I am just a bit short on time to do it my self.

In general i only updated the symbol and footprint links. I do not plan to do anything else with these. I will take a look at the rasbperry template. (redraw the zone and resave it.)

These are not planned to be released for version 4.

**Comment by evanshultz** [comment]
I figured as much. For me, they're fine to use as-is. I'll wait for you to update the zone before I merge.

Should I create an issue to capture the feedback above in case someone wants to review these later?

**Comment by poeschlr** [comment]
An issue might be a good idea.

It might also be a good idea to change them such that the schematic does use a hierarchical sheets. If i find time i might make one as an example. (But will definitely be a different pull request.)

**Comment by poeschlr** [comment]
Ok i redrew the raspberry pi hat zones.

You can also add to the list of bad things that the raspberry pi hat is extremly bad regarding EMC.
It has a dedicated layer for gnd (one of the inner layers) but does not use vias to connect to it such that return paths are short. It also has horrible settings for clearance and min width for the zones -> results in no short connection in the area of the pin header. Which would be quite important.

**Comment by evanshultz** [comment]
@poeschlr 
Thanks! What about the third item? This template name seems weird and doesn't conform to all the others.

**Comment by evanshultz** [comment]
And the second item. That would be more clear. But if no for one or both items, I will merge.

**Comment by evanshultz** [comment]
@poeschlr Great! Ready for merge?

**Comment by poeschlr** [comment]
I renamed the two templates as by your suggestions. Should now be ready to merge.

**Pull request merged**
