### PR TITLE
Worksheet templates for KiCad

### PR DESCRIPTION
**Pull request by erasmo1982**
Worksheet templates for KiCad according to standards ISO 5457 and ISO 7200

### CODE REVIEW

**Comment by evanshultz** [comment]
@erasmo1982 
First, thanks for contributing to KiCad!

I'm not familiar with these standards and just read them today, so please forgive any misunderstandings on my part. It appears 5457 covers page sizes without the title block details while 7200 is a complimentary document covering the data fields inside the title block. 5457:1999 and 7200:2004 are the latest revisions.

I will start with some questions/thoughts:
1. Templates are not just worksheets. They need to go somewhere else, but I don't know where now. We can continue to fix up this PR but that will have to be figured out before merging this.
1. Are you able to open these in Eeschema? If so, how?
1. ISO 7200 is a part of this entire sheet but not mentioned? And the specified sheet Designation is not being respected. Put together, perhaps it should be called `DrawingSheetISO5457-A1U_ISO7200`?
1. Is there a way to make a comment in a worksheet? If so, the exact ISO standards and the year of revision should be included.
1. Was there a specific reason to omit A0 and A1?
1. `comp` is for the Compact ISO 7200 title block. Write out the full word for clarity.
1. The "portrait" worksheets don't appear to be in portrait format for me; the title block should fill up the entire bottom section of the sheet in A4 portrait:
image
1. The dimensions seem to be just a bit off. For example, let's look at `ISO5457_A4.kicad_wks`. I measure a1=200, b1=277, a2=190, b2=267, a3=210, b3=297. Am I doing something wrong which is causing my numbers to be off? I see all sheets have the same dimension, though, so maybe there's something weird in the editor and the actual dimensions isn't what is shown in PL Editor.
1. Centring marks extend into the drawing frame only 5mm, not 10mm.
1. Grid references should be on left, right, top, and bottom. Only left and top and shown now on A4 sheets.
1. Grid reference letters/numbers are 3mm and should be 3.5mm.
1. The appropriate grid reference fields are only used for A4. Bigger sheets do not have enough fields.
1. It appears the rightmost grid reference on the bottom should be the sheet size.

@poeschlr 
Can you take a look?

Some questions:
1.  We do have a few worksheets at https://github.com/KiCad/kicad-templates but I'm not aware of a designated place for them. Should they live in GH? If so, where? Do we need a new repo?
1. Many worksheets are present in Eeschema's Page Settings dialog, but I don't see discrete files anywhere on my local PC. I would think ISO sheets could replace or add to the existing ones. Do we need to contact the devs about that?

**Comment by nickoe** [comment]
I think having the page layout in this repository is fine. I consider the kicad_wks as a form of template, although it is not a project template in the same form as a project template as for example a shield to something.

**Comment by stambaughw** [comment]
I'm fine with adding page layouts to the template repository.  If the
root folder gets too crowded, we can always move the page layouts to a
separate folder.

**Comment by poeschlr** [comment]
This contributions adds a sub folder to the root folder. I assume something needs to be done to the cmake files to add these to the installation as well. (otherwise they would need to be moved to the root folder)

**Comment by evanshultz** [comment]
@erasmo1982 
Can you please use descriptive commit messages? "Worksheet templates for KiCad" for every commit doesn't describe the exact changes.

@stambaughw 
There are a number of page layouts included with KiCad but I don't see discrete .kicad_wks files in the user or install directories. Is there a way to add custom page layouts to the default list?

**Comment by erasmo1982** [comment]
@evanshultz 
I have described the changes in the optional extended description. The last commit is described as 'Updated text height in grid reference'.

**Comment by nickoe** [comment]
It looks like there are issues with the grid numbers and letters. Why are they not using the repeat operators instead of being individual text labels?

**Comment by evanshultz** [comment]
Big fat tick marks (if you mean the ones in the center of each side) are in the ISO 5457:1999 spec. See section 4.3.

**Comment by erasmo1982** [comment]
@nickoe I have not detected any bug to fix in the templates, so no updates are expected.

**Comment by nickoe** [comment]
@erasmo1982 But why are the coordinate numbers not filling the whole page, and why are they set as individual test strings?

It is visible on the image in https://github.com/KiCad/kicad-templates/pull/13#issuecomment-398188629  the horizontal only goes to 4 while there seem to be more space.

**Comment by evanshultz** [comment]
@erasmo1982 
And I asked quite a number of questions about with many missing responses from you. I would also like to get this merged.

**Comment by erasmo1982** [comment]
@nickoe coordinate numbers are not filling the whole page in #13 because the screenshot shows an A4 portrait template drawn over an A4 landscape paper size. Coordinate numbers and letters are set as individual text strings for simplicity.

@evanshultz sorry for the delay. I try to answer your questions below:

> Templates are not just worksheets. They need to go somewhere else, but I don't know where now. 
We can continue to fix up this PR but that will have to be figured out before merging this.

In my opinion, the proper place for the templated is the kicad-templates folder

> Are you able to open these in Eeschema? If so, how?

You must select the paper size firstly, and then select the appropriate template. This is because centring marks are different for each paper size.

> ISO 7200 is a part of this entire sheet but not mentioned? And the specified sheet Designation is not being respected. Put together, perhaps it should be called DrawingSheetISO5457-A1U_ISO7200?

Yes, I think both standards should be included in the designation.

> Is there a way to make a comment in a worksheet? If so, the exact ISO standards and the year of revision should be included.

I do not understand what do you mean with make a comment in a worksheet. I agree the exact ISO standards and the year of the revision should be included.

> Was there a specific reason to omit A0 and A1?

I usually draw my schematics in A4, A3 or A2 paper size. I think A1 and A0 are not so useful because of their sizes, however they may be included in the future.

> comp is for the Compact ISO 7200 title block. Write out the full word for clarity.

Ok, I thought it was clear enough. Please feel free to update the designations.

> The "portrait" worksheets don't appear to be in portrait format for me; the title block should fill up the entire bottom section of the sheet in A4 portrait

You should select the correct template for each paper size. In the screenshot an A4 portrait template have been loaded over an A4 landscape paper size.

> The dimensions seem to be just a bit off. For example, let's look at ISO5457_A4.kicad_wks. I measure a1=200, b1=277, a2=190, b2=267, a3=210, b3=297. Am I doing something wrong which is causing my numbers to be off? I see all sheets have the same dimension, though, so maybe there's something weird in the editor and the actual dimensions isn't what is shown in PL Editor.

I think dimensions are right. Please check [this reference about layout](https://cadsetterout.com/tag/size-and-layout-of-drawing-sheets/), [this one about title block](http://tolerancing.net/engineering-drawing/title-block.html) and [this one about revisions block](http://tolerancing.net/engineering-drawing/revisions-block.html).

> Centring marks extend into the drawing frame only 5mm, not 10mm.

If I am not mistaken, centring marks should be 10mm wide.

> Grid references should be on left, right, top, and bottom. Only left and top and shown now on A4 sheets.

If I am not mistaken, grid references for A4 portrait, the one which appears in the screenshot, may be written in the top and left margins only.

> Grid reference letters/numbers are 3mm and should be 3.5mm.

It has been fixed in the most recent commit.

> The appropriate grid reference fields are only used for A4. Bigger sheets do not have enough fields.

If a bigger paper size is defined and the appropriate template is selected, all grid reference fields will be shown.

> It appears the rightmost grid reference on the bottom should be the sheet size.

I have seen this sometimes, but I am not sure if it s mandatory.

**Comment by antoniovazquezblanco** [comment]
What is the status on this issue? What is needed to move it forward?

**Comment by evanshultz** [comment]
I have had this tab open for a while and the ball is in my court. My end goal is to merge this and then request the devs add them to the default list of page layouts in KiCad.

**Comment by antoniovazquezblanco** [comment]
I haven't had a look at this repo. I use templates little to nothing. Having a look at this repo I found that you plan to include worksheet templates in folders that can be confused with project templates. I was planning on finishing this PR and making a proposal to split things into a better structure before talking to the devs.

What do you think?

**Comment by poeschlr** [comment]
@antoniovazquezblanco and @evanshultz  This seems to have been forgotten for a while.

Regarding organization: We either need a separate repo ro add two subfolders to this one. One for worksheet templates and one for project templates. (The cmake file would need updating as soon as this is done.)

This reorg should however happen separately from this pull request. The templates provided here should simply go into a well named sub-folder that indicates that it holds worksheet templates. (Not the case right now.)

**Comment by antoniovazquezblanco** [comment]
I also think that reorganization should take place. Having a repo for templates I would divide the repo into two subfolders to avoid problems with packagers and to simplify their jobs. I don't think this is big enought yet to make it two separate repos.

**Comment by antoniovazquezblanco** [comment]
Repo has been reorganized. @erasmo1982 could you please move the templates to the worksheet folder?

Thanks!

**Comment by erasmo1982** [comment]
@antoniovazquezblanco sure!

**Comment by antoniovazquezblanco** [comment]
Closing this in favour of that PR

**Pull request closed without merging**
